name: docker-ci-pipeline
on: push
jobs:
  dockerci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
      - name: Build image
        run: docker build -t ${{vars.DOCKER_USERNAME }}/helloworld-demo-python:vj .
      - name: Verify the image 
        run: docker images
      - name: Create Container 
        run: docker run --name pythonContainer -itd -p 8080:8080 ${{vars.DOCKER_USERNAME }}/helloworld-demo-python:vj
      - name: Waiting Time
        run: sleep 20
      - name: View Container        
        run: docker ps
      - name: Check output
        run: curl -f http://localhost:8080
      - name: Docker login 
        uses: docker/login-action@v3.6.0
        with:
          username: ${{vars.DOCKER_USERNAME }}
          password: ${{secrets.DOCKER_TOKEN }}
 
      - name: Push the image
        run: docker push ${{vars.DOCKER_USERNAME }}/helloworld-demo-python:vj
      - name: Docket cleanup
        run: docker rm pythonContainer
 
